/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HrItzW5SGnX
 */


import { useState } from 'react';
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import axios from 'axios';

export function AdCampaign() {
  const [formData, setFormData] = useState({
    advertiserName: '',
    productName: '',
    campaignBriefs: ''
  });

  const handleChange = (e:any) => {
    const { id, value } = e.target;
    setFormData(prevState => ({
      ...prevState,
      [id]: value
    }));
  };

  const handleSubmit = async (e:any) => {
    e.preventDefault();
    try {
      const response = await axios.post('http://127.0.0.1:8001/get-data', formData);
      console.log('Server response:', response.data);
    } catch (error) {
      console.error('Error submitting form:', error);    }
  };

  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center space-y-4 text-center">
          <div className="space-y-2">
            
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
              Advertiser Information
            </h1>
            <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              Please enter the details of the advertiser.
            </p>
          </div>
          <div className="w-full max-w-sm space-y-2">
            <form className="flex flex-col space-y-4" onSubmit={handleSubmit}>
              <div className="grid w-full gap-1.5">
                <Label htmlFor="advertiser-name">Advertiser Name</Label>
                <Input id="advertiserName" placeholder="Enter Advertiser Name" onChange={handleChange} value={formData.advertiserName} />
              </div>
              <div className="grid w-full gap-1.5">
                <Label htmlFor="product-name">Product Name</Label>
                <Input id="productName" placeholder="Enter Product Name" onChange={handleChange} value={formData.productName} />
              </div>
              <div className="grid w-full gap-1.5">
                <Label htmlFor="campaign-briefs">Campaign Briefs</Label>
                <Textarea className="min-h-[100px]" id="campaignBriefs" placeholder="Enter Campaign Briefs" onChange={handleChange} value={formData.campaignBriefs} />
              </div>
              <Button className="w-full" type="submit">
                Submit
              </Button>
            </form>
          </div>
        </div>
      </div>
    </section>
  );
}
