/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/x1NCeNBjGXX
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function AdCreate() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Advertising Details</CardTitle>
        <CardDescription>Please fill out the form below with your advertising details.</CardDescription>
      </CardHeader>
      <CardContent>
        <form className="grid w-full items-center gap-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="advertiser-name">Advertiser Name</Label>
              <Input id="advertiser-name" placeholder="Enter your name" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="advertiser-company">Advertiser Company</Label>
              <Input id="advertiser-company" placeholder="Enter your company" />
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="advertiser-contact">Advertiser Contact</Label>
            <Input id="advertiser-contact" placeholder="Enter your contact details" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="product-name">Product Name</Label>
            <Input id="product-name" placeholder="Enter the product name" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="campaign-brief">Campaign Brief</Label>
            <Textarea className="min-h-[100px]" id="campaign-brief" placeholder="Enter your campaign brief" />
          </div>
        </form>
      </CardContent>
      <CardFooter className="flex justify-end">
        <Button>Submit</Button>
      </CardFooter>
    </Card>
  )
}
